# ==============================================================================
# PyPSA-NZA-DATA Dynamic Data Processing Configuration
# ==============================================================================
# This file controls the processsing of time-series (monthly) datasets downloaded 
# from the Electricity Authority's EMI website.
#
# ==============================================================================


# ------------------------------------------------------------------------------
# INPUT AND OUTPUT DIRECTORIES
# Paths relative to project root. Use {year} placeholder for year-specific dirs.
# ------------------------------------------------------------------------------
paths:
#   root:     "/home/pbrun/{{enter sub-dir name}}"  # Linux work-space directory: user spec
    root:       "C:/Users/Public/Documents/Thesis/analysis"  # Windows work-space directory: user spec
    gen_in:     "data/raw/2024/gen/"
    gen_out:    "data/processed/2024/gen/cons_MWh/"
    import_in:  "data/raw/2024/import/"
    import_out: "data/processed/2024/import/cons_MWh/"
    export_in:  "data/raw/2024/export/"
    export_out: "data/processed/2024/export/cons_MWh/"
    hvdc_in:    "data/raw/2024/hvdc/"
    hvdc_out:   "data/processed/2024/hvdc/cons_MWh/"
    react_in:   "data/raw/2024/react/"
    react_out:  "data/processed/2024/react/cons_MWh/"



grid_energy_types:
   - gen
   - export
   - import
   - hvdc
   - react

# ------------------------------------------------------------------------------
# SCALE FACTOR
# Converts from kWh to MWh by multiplying all data by 0.001
# ------------------------------------------------------------------------------
scale_factor : 1.0e-3


