# rootdir: "/home/pbrun/"   # LINuX
rootdir: "C://Users/Public/Documents/Thesis/analysis"
logs:    "logs"
inpdir:  "data/raw/static/"
outdir:  "data/processed/static/"

sites_inp: "sites.csv"
sites_out: "sites.csv"

trans_inp: "transmission_lines.csv"
trans_out: "trans_lines.csv"

pocs_inp: "NetworkSupplyPointsTable.csv"
pocs_out: "pocs.csv"

gen_inp: "20250917_DispatchedGenerationPlant.csv"
gen_out: "generators.csv"
